### ISSUE TITLE
AdvancedAssert unstable

### ISSUE THREAD

**Issue by simPod** [cdn77/TestUtils#14]
- [ ] needs tests
- [ ] needs docs

TBH I have no idea how to use it and I don't use it. Is it worth maintaining?

**Comment by grongor** [comment]
Co znamená unstable? A jak nechápeš jak to používat? :D Vždyť to mají v názvu, co dělají...

**Comment by simPod** [comment]
Neni to otestovany a kdyz jsem to pouzil, tak to vetsinou fungovalo jen na ten specifickej case, na kterej to bylo vytvoreny. Takze ten muj uz to nepodporovalo. Takze pro lib to neni uplne vhodny pac checklist viz issue no.

**Comment by grongor** [comment]
Možná by bylo dobrý začít tím pro jakej usecase ti to nefungovalo :D Mě se ještě nestalo, že by to nefungovalo na to na co to má fungovat (dle jména), takže spíš od toho čekáš něco jinýho nebo to používáš špatně :D

**Comment by simPod** [comment]
Ja rikam, ze to nema dokumentaci a testy, to je true story, ne? 

Nepouzivam to, parkrat jsem zkusil a neuspesne. Mbmb (might be my bad), ale nemam si to kde zjitit - pac nemam docs ani testy :D - a zkoumat source jsem byl uz linej.

**Comment by grongor** [comment]
Yes, to je true, já reagoval na "TBH I have no idea how to use it and I don't use it. Is it worth maintaining?"

Zjistit jak to použít jde z míst kde je to použitý. A pokud seš línej zkoumat source, tak to je těžký no :D To že to nemá docs se holt může stát, když to je copy-paste z interního toolingu :D Není to ofc dobře :) Just saying, že není důvod být překvapenej :D

**Comment by simPod** [comment]
A jak to teda budem udrzovat? Ja to asi resit uplne nechci, v testech jsem pro to ani nemel potrebu, takze uplne nemam motivaci. Idealne bych to ted hodil do vetve vedle a z masteru smazal. Blokuje to nasazeni psalmu napr.
